name: Bulk Delete Runs
on:
  workflow_dispatch: # Allows manual trigger

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: iamazeem/delete-workflow-runs-action@v1
        with:
          keep: 0 # Deletes everything
